# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2015
use_https: true

# Custom your favicon.ico in `site/source`
favicon: /files/favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: /atom.xml

# ===========================================
# Menu Settings
# ===========================================
menu:
  - text: 首页
    link: /
    hideOnMobile: true
  - text: 归档
    link: /archives
    hideOnMobile: false
  - text: 留言
    link: /messages
    hideOnMobile: false
  - text: 关于
    link: /about
    hideOnMobile: false
  - text: KTORM
    link: https://www.ktorm.org/zh-cn
    hideOnMobile: true

# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>testing...</p>
widget:
  Tags: true
  Categories: false
  Custom: false

widget_custom:
  title: Test
  content: <p>testing...</p>

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  fancybox: false

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics: UA-180345721-1

# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname:


# ===========================================
# Version
# ===========================================
version: 1.1
